### ISSUE TITLE
Feature Request: Cannot merge array inputs

### ISSUE THREAD

**Issue by 0xThemis** [TaceoLabs/co-snarks#106]
At the moment, we can only merge inputs from multiple parties if it is a dedicated named input. If a circuit has inputs like:

`signal input in[2]`;

it is not possible to provide the array from different parties

- [ ] Implementation
- [ ] Docs example

**Comment by dkales** [comment]
Use "?" as placeholder for other parties.

**Comment by fabian1409** [comment]
> @fabian1409 is this done?

will implement this next week
