### ISSUE TITLE
Shamir correlated randomness generation perfomance unstable

### ISSUE THREAD

**Issue by fabian1409** [TaceoLabs/co-snarks#206]
After the refactor, the corr rand pair generation happen all at once and before we construct a ShamirProtocol
This should be faster than doing it batched because we do less network rounds but with more data at once (especially in high latency environments)

However, most of the time, one party seems to be fast, while others take more than twice as long.
Sometimes all parties are fast.

Might have something to do with our network implementation (already tried with s2n-quic, another quic lib, made no difference)

**Comment by dkales** [comment]
Think this is mostly obsolete by now
